services:
  mcp-wasmpython-runner:
    build:
      dockerfile: Dockerfile
    restart: always
    container_name: mcp-wasmpython-runner
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync+restart
          path: ./mcp-wasmpython-runner
          target: /opt/mcp-wasmpython-runner