[project]
name = "mcp-cpp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiofiles>=24.1.0",
    "mcp[cli]>=1.6.0",
    "types-aiofiles>=24.1.0.20250326",
]
